spring:
  application:
    name: spring
  datasource:
    url: jdbc:mysql://localhost:3306/nkz20030419?useSSL=false&serverTimezone=UTC
    username: root
    password: nkz20030419
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 3000