spring:
  application:
    name: spring
  datasource:
    url: jdbc:mysql://localhost:3306/kob?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: nkz20030419
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 3000